version: '3.8'
services:
  redis:
    image: redis:7
    ports: ['6379:6379']
  mongo:
    image: mongo:6
    ports: ['27017:27017']
  ingestion:
    build: ./services/ingestion-service
    environment:
      - AV_KEY=${AV_KEY}
      - REDIS_URL=redis://redis:6379
  alert-engine:
    build: ./services/alert-engine
    environment:
      - MONGO_URL=mongodb://mongo:27017/stock
      - REDIS_URL=redis://redis:6379
  api-server:
    build: ./services/api-server
    environment:
      - MONGO_URL=mongodb://mongo:27017/stock
      - REDIS_URL=redis://redis:6379
